language: c
before_install:
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo apt-get install libglib2.0-dev
before_script:
  - cd src
script:
  - gcc --version
  - pwd
  - ls
  - sudo sh ./utest.sh